### ISSUE TITLE
Input matrix format / pandas 1.0.4 compatibility

### ISSUE THREAD

**Issue by jr-leary7** [pavlin-policar/openTSNE#136]
##### Expected behavior
I've formatted the input to the `tsne.fit()` call as a `pandas` dataframe, with principal components as columns and cells as rows. I expected the function to execute as detailed in the tutorial, but I received an error having to do with `pandas`. 

##### Actual behaviour
I'm not entirely sure if the error is due to the way I formatted the input dataframe, or if it's a problem with `v1.0.4` of `pandas`. This is the error (apologies in advance for the text wall):

```
File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2646, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 0
```

Which in turn causes another `KeyError`, which is:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/openTSNE/tsne.py", line 1156, in fit
    embedding = self.prepare_initial(X)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/openTSNE/tsne.py", line 1209, in prepare_initial
    verbose=self.verbose,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/openTSNE/affinity.py", line 138, in __init__
    data, method, k_neighbors, metric, metric_params, n_jobs, random_state, verbose
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/openTSNE/affinity.py", line 319, in build_knn_index
    neighbors, distances = knn_index.build(data, k=k)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/openTSNE/nearest_neighbors.py", line 211, in build
    self.index.add_item(i, data[i])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 0
```
##### Steps to reproduce the behavior
I'm using `pandas v1.0.4` and `openTSNE v0.4.3`. Any advice on how to proceed?

**Comment by jr-leary7** [comment]
EDIT: I re-formatted the `DataFrame` as a `NumPy` array, and the algorithm worked as expected. Maybe add a line in the README specifying that an array is expected as input (if that is the case)?

**Comment by pavlin-policar** [comment]
Hi, thanks for reporting this and your interest in openTSNE. While the expected usage is definitely to use numpy arrays, I am somewhat surprised this doesn't work. However, looking at the logs, the error makes sense -- pandas indexing is different from numpy.

The main goal is a mostly similar interface to scikit-learn, so I'll check how they handle it. I definitely won't add pandas as a hard dependency for this use case alone and the fix should be entirely trivial, passing `df.values` instead of just `df`, which, in my experience, is also quite standard in the Python ecosystem.

Either way, I'm glad you figured it out.
