### ISSUE TITLE
Issue using custom metric

### ISSUE THREAD

**Issue by jdtuck** [pavlin-policar/openTSNE#153]
I just installed on a new machine and have installed pynndescent 0.5.1 and I am getting this error. I am using the latest version off of github.

```
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-16-8d7d25ecf5ce> in <module>
----> 1 metrics_fr = train_classifier_fr(z1, y, 5, idx)

/home/jdtuck/Documents/Research/elastic_umap/Code/tsne_classify_part.py in train_classifier_fr(x, y, n_splits, split, n_components, seed)
    136                         RandomForestClassifier(random_state=np.random.RandomState(seed),n_jobs=-1))
    137
--> 138     metrics = train_cv(clf, x, y, skf, split)
    139
    140     return metrics

/home/jdtuck/Documents/Research/elastic_umap/Code/tsne_classify_part.py in train_cv(clf, x, y, cv, split)
    102         x_val, y_val = get_split(i_val, x, y)
    103
--> 104         clf.fit(x_train, y_train)
    105
    106         y_hat_train = clf.predict(x_train)

~/.conda/envs/umap/lib/python3.8/site-packages/sklearn/pipeline.py in fit(self, X, y, **fit_params)
    328         """
    329         fit_params_steps = self._check_fit_params(**fit_params)
--> 330         Xt = self._fit(X, y, **fit_params_steps)
    331         with _print_elapsed_time('Pipeline',
    332                                  self._log_message(len(self.steps) - 1)):

~/.conda/envs/umap/lib/python3.8/site-packages/sklearn/pipeline.py in _fit(self, X, y, **fit_params_steps)
    290                 cloned_transformer = clone(transformer)
    291             # Fit or load from cache the current transformer
--> 292             X, fitted_transformer = fit_transform_one_cached(
    293                 cloned_transformer, X, y, None,
    294                 message_clsname='Pipeline',

~/.conda/envs/umap/lib/python3.8/site-packages/joblib/memory.py in __call__(self, *args, **kwargs)
    350
    351     def __call__(self, *args, **kwargs):
--> 352         return self.func(*args, **kwargs)
    353
    354     def call_and_shelve(self, *args, **kwargs):

~/.conda/envs/umap/lib/python3.8/site-packages/sklearn/pipeline.py in _fit_transform_one(transformer, X, y, weight, message_clsname, message, **fit_params)
    738     with _print_elapsed_time(message_clsname, message):
    739         if hasattr(transformer, 'fit_transform'):
--> 740             res = transformer.fit_transform(X, y, **fit_params)
    741         else:
    742             res = transformer.fit(X, y, **fit_params).transform(X)

~/.conda/envs/umap/lib/python3.8/site-packages/openTSNE-0.4.4-py3.8-linux-x86_64.egg/openTSNE/sklearn.py in fit_transform(self, X, y)
     34
     35         """
---> 36         embedding = super().fit(X)
     37         self.embedding_ = embedding
     38         return self.embedding_.view(np.ndarray)

~/.conda/envs/umap/lib/python3.8/site-packages/openTSNE-0.4.4-py3.8-linux-x86_64.egg/openTSNE/tsne.py in fit(self, X)
   1199             print("-" * 80, repr(self), "-" * 80, sep="\n")
   1200
-> 1201         embedding = self.prepare_initial(X)
   1202
   1203         try:

~/.conda/envs/umap/lib/python3.8/site-packages/openTSNE-0.4.4-py3.8-linux-x86_64.egg/openTSNE/tsne.py in prepare_initial(self, X)
   1245
   1246         if self.affinities is None:
-> 1247             affinities = PerplexityBasedNN(
   1248                 X,
   1249                 self.perplexity,

~/.conda/envs/umap/lib/python3.8/site-packages/openTSNE-0.4.4-py3.8-linux-x86_64.egg/openTSNE/affinity.py in __init__(self, data, perplexity, method, metric, metric_params, symmetrize, n_jobs, random_state, verbose)
    135
    136         k_neighbors = min(self.n_samples - 1, int(3 * self.perplexity))
--> 137         self.knn_index, self.__neighbors, self.__distances = build_knn_index(
    138             data, method, k_neighbors, metric, metric_params, n_jobs, random_state, verbose
    139         )

~/.conda/envs/umap/lib/python3.8/site-packages/openTSNE-0.4.4-py3.8-linux-x86_64.egg/openTSNE/affinity.py in build_knn_index(data, method, k, metric, metric_params, n_jobs, random_state, verbose)
    317         )
    318
--> 319     neighbors, distances = knn_index.build(data, k=k)
    320
    321     return knn_index, neighbors, distances

~/.conda/envs/umap/lib/python3.8/site-packages/openTSNE-0.4.4-py3.8-linux-x86_64.egg/openTSNE/nearest_neighbors.py in build(self, data, k)
    381             n_neighbors_build = 15
    382
--> 383         self.index = pynndescent.NNDescent(
    384             data,
    385             n_neighbors=n_neighbors_build,

~/.conda/envs/umap/lib/python3.8/site-packages/pynndescent/pynndescent_.py in __init__(self, data, metric, metric_kwds, n_neighbors, n_trees, leaf_size, pruning_degree_multiplier, diversify_prob, n_search_trees, tree_init, init_graph, random_state, low_memory, max_candidates, n_iters, delta, n_jobs, compressed, verbose)
    901                 print(ts(), "NN descent for", str(n_iters), "iterations")
    902
--> 903             self._neighbor_graph = nn_descent(
    904                 self._raw_data,
    905                 self.n_neighbors,

~/.conda/envs/umap/lib/python3.8/site-packages/numba/core/dispatcher.py in _compile_for_args(self, *args, **kws)
    413                 e.patch_message(msg)
    414
--> 415             error_rewrite(e, 'typing')
    416         except errors.UnsupportedError as e:
    417             # Something unsupported is present in the user code, add help info

~/.conda/envs/umap/lib/python3.8/site-packages/numba/core/dispatcher.py in error_rewrite(e, issue_type)
    356                 raise e
    357             else:
--> 358                 reraise(type(e), e, None)
    359
    360         argtypes = []

~/.conda/envs/umap/lib/python3.8/site-packages/numba/core/utils.py in reraise(tp, value, tb)
     78         value = tp()
     79     if value.__traceback__ is not tb:
---> 80         raise value.with_traceback(tb)
     81     raise value
     82

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
Internal error at <numba.core.typeinfer.CallConstraint object at 0x7fc760a35f10>.
too many positional arguments
During: resolving callee type: type(CPUDispatcher(<function efda_distance at 0x7fc7b16ce790>))
During: typing of call at /ascldap/users/jdtuck/.conda/envs/umap/lib/python3.8/site-packages/pynndescent/pynndescent_.py (748)

Enable logging at debug level for details.

File "../../../../../../ascldap/users/jdtuck/.conda/envs/umap/lib/python3.8/site-packages/pynndescent/pynndescent_.py", line 748:
            def _partial_dist_func(x, y):
                return _distance_func(x, y, *dist_args)
                ^

During: resolving callee type: type(CPUDispatcher(<function NNDescent.__init__.<locals>._partial_dist_func at 0x7fc7b0761160>))
During: typing of call at /ascldap/users/jdtuck/.conda/envs/umap/lib/python3.8/site-packages/pynndescent/pynndescent_.py (83)

During: resolving callee type: type(CPUDispatcher(<function NNDescent.__init__.<locals>._partial_dist_func at 0x7fc7b0761160>))
During: typing of call at /ascldap/users/jdtuck/.conda/envs/umap/lib/python3.8/site-packages/pynndescent/pynndescent_.py (83)

During: resolving callee type: type(CPUDispatcher(<function NNDescent.__init__.<locals>._partial_dist_func at 0x7fc7b0761160>))
During: typing of call at /ascldap/users/jdtuck/.conda/envs/umap/lib/python3.8/site-packages/pynndescent/pynndescent_.py (83)


File "../../../../../../ascldap/users/jdtuck/.conda/envs/umap/lib/python3.8/site-packages/pynndescent/pynndescent_.py", line 83:
def generate_leaf_updates(leaf_block, dist_thresholds, data, dist):
    <source elided>

                d = dist(data[p], data[q])
                ^

During: resolving callee type: type(CPUDispatcher(<function generate_leaf_updates at 0x7fc7609e91f0>))
During: typing of call at /ascldap/users/jdtuck/.conda/envs/umap/lib/python3.8/site-packages/pynndescent/pynndescent_.py (110)

During: resolving callee type: type(CPUDispatcher(<function generate_leaf_updates at 0x7fc7609e91f0>))
During: typing of call at /ascldap/users/jdtuck/.conda/envs/umap/lib/python3.8/site-packages/pynndescent/pynndescent_.py (110)


File "../../../../../../ascldap/users/jdtuck/.conda/envs/umap/lib/python3.8/site-packages/pynndescent/pynndescent_.py", line 110:
def init_rp_tree(data, dist, current_graph, leaf_array):
    <source elided>

        updates = generate_leaf_updates(
        ^

During: resolving callee type: type(CPUDispatcher(<function init_rp_tree at 0x7fc760b0cb80>))
During: typing of call at /ascldap/users/jdtuck/.conda/envs/umap/lib/python3.8/site-packages/pynndescent/pynndescent_.py (365)

During: resolving callee type: type(CPUDispatcher(<function init_rp_tree at 0x7fc760b0cb80>))
During: typing of call at /ascldap/users/jdtuck/.conda/envs/umap/lib/python3.8/site-packages/pynndescent/pynndescent_.py (365)


File "../../../../../../ascldap/users/jdtuck/.conda/envs/umap/lib/python3.8/site-packages/pynndescent/pynndescent_.py", line 365:
def nn_descent(
    <source elided>
        if rp_tree_init:
            init_rp_tree(data, dist, current_graph, leaf_array)
```

**Comment by jdtuck** [comment]
error on my end
