### ISSUE TITLE
import problem

### ISSUE THREAD

**Issue by xiangruyimoxiaoyangyang** [pavlin-policar/openTSNE#58]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\annaconde\envs\tensorflow\lib\site-packages\openTSNE\__init__.py", line 3, in <module>
    from .tsne import TSNE, TSNEEmbedding, PartialTSNEEmbedding, OptimizationInterrupt
  File "D:\annaconde\envs\tensorflow\lib\site-packages\openTSNE\tsne.py", line 744
    raise ValueError(f"Unrecognized initialization scheme `{initialization}`.")
                                                                             ^
SyntaxError: invalid syntax

**Comment by pavlin-policar** [comment]
Please note that you need Python 3.6 or higher to use openTSNE.
